"""
Django settings for corefit project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'nm(%mw6rru5m@%3m#u0-(rgu=_0^i_rl0lx7adsy9b(7pbwx!l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['162.241.71.136']

LOGIN_URL = '/login'

LOGIN_PROFILE = '/profile'
LOGIN_PTFREELANCER_PROFILE = '/freelancer-profile'
LOGIN_PTEMPLOYEE_PROFILE = '/ptemployee-profile'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gymstudio'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # login middleware
    'gymstudio.middleware.LoginRequiredMiddleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'corefit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "corefit.config.context_processors.constant",
            ],
            'libraries':{
                'define_action': 'gymstudio.define_action',
                'split': 'gymstudio.split',
                'getType': 'gymstudio.getType',
                'fetch_user': 'gymstudio.tags.fetch_user',
                'change_type': 'gymstudio.tags.change_type',
            
            }
        },
    },
]

WSGI_APPLICATION = 'corefit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

#DATABASES = {
 #   'default': {
  #      'ENGINE': 'django.db.backends.sqlite3',
   #     'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    'default': {
        'NAME': 'nimbleap_corefit_new',
        'ENGINE': 'django.db.backends.mysql',
        'USER': 'nimbleap_corefit_new',
        'PASSWORD': 'Corefit@123',
        'HOST': 'localhost',
        'OPTIONS': {
          'autocommit': True,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_EXEMPT_URLS = (
    r'^login',
    r'^forgot-password',
    r'^forgot_otp_verify',
    r'^otp_send',
    r'^otp_verify',
    r'^reset-password',
    r'^checkValid',
    r'^thank-you',
    r'^scookie',
    r'^setcookie',
    r'^register'
)


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

SITE_TITLE = 'CoreFit'
HTTP_PATH = 'http://162.241.71.136:8001' 
LOGO = 'static/images/logo-before-login.png'
LOGO_INNER = 'static/images/Corefit-logo.png'
REPLY_EMAIL = 'info@corefit.com'
REPLY_PHONE = '(971) 4 236 4658'
MAIL_SIGNATURE = 'Corefit Team'

FACILITY_TYPE  = {
    'Gym': 'Gym',
    'Studio': 'Studio',
    'Both': 'Both',
}

STATIC_URL = 'static/'

STATICFILES_DIRS=[BASE_DIR,"static"]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
